### ISSUE TITLE
友盟更新了，自动更新的功能已经关闭了。

### ISSUE THREAD

**Issue by SheepYang1993** [chentao0707/SimplifyReader#91]

**Comment by lvranf** [comment]
注释友盟相关编译不通过的代码，程序能成功安装，但无法启动，报错java.lang.UnsatisfiedLinkError: Couldn't load luajava from loader dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/com.github.obsessive.simplifyreader-1.apk"]
at com.youku.player.YoukuPlayerBaseApplication.onCreate(YoukuPlayerBaseApplication.java:35)
at com.github.obsessive.simplifyreader.SimplifyReaderApplication.onCreate(SimplifyReaderApplication.java:38)

请教解决办法！

**Comment by zhaozhuzi** [comment]
+1

**Comment by Zhangxd77** [comment]
+1
